/* Tables */


CREATE TABLE DIPENDENTE (
    N_Badge INTEGER NOT NULL,
    Nome INTEGER NOT NULL,
    Cognome INTEGER NOT NULL,
    Password INTEGER NOT NULL,
    PRIMARY KEY (N_Badge)
);
CREATE TABLE CLIENTE (
    Email INTEGER NOT NULL,
    Nome INTEGER NOT NULL,
    Cognome INTEGER NOT NULL,
    Password INTEGER NOT NULL,
    Telefono INTEGER NOT NULL,
    PRIMARY KEY (Email)
);
CREATE TABLE LAVORO (
    ID_Lavoro INTEGER NOT NULL,
    DurataPrevista INTEGER NOT NULL,
    Titolo INTEGER NOT NULL,
    Descrizione INTEGER NOT NULL,
    Prezzo INTEGER NOT NULL,
    PRIMARY KEY (ID_Lavoro)
);
CREATE TABLE APPUNTAMENTO (
    ID_Appuntamento INTEGER NOT NULL,
    modello INTEGER NOT NULL,
    tipoAutoMoto INTEGER NOT NULL,
    targa INTEGER NOT NULL,
    dataOra INTEGER NOT NULL,
    CLIENTE_Email INTEGER NOT NULL,
    PRIMARY KEY (ID_Appuntamento),
    FOREIGN KEY (CLIENTE_Email) REFERENCES CLIENTE (Email)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE COMPOSTO_DA (
    APPUNTAMENTO_ID_Appuntamento INTEGER NOT NULL,
    LAVORO_ID_Lavoro INTEGER NOT NULL,
    PRIMARY KEY (APPUNTAMENTO_ID_Appuntamento, LAVORO_ID_Lavoro),
    FOREIGN KEY (APPUNTAMENTO_ID_Appuntamento) REFERENCES APPUNTAMENTO (ID_Appuntamento)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (LAVORO_ID_Lavoro) REFERENCES LAVORO (ID_Lavoro)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
CREATE TABLE SVOLGE (
    DIPENDENTE_N_Badge INTEGER NOT NULL,
    LAVORO_ID_Lavoro INTEGER NOT NULL,
    PRIMARY KEY (DIPENDENTE_N_Badge, LAVORO_ID_Lavoro),
    FOREIGN KEY (DIPENDENTE_N_Badge) REFERENCES DIPENDENTE (N_Badge)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (LAVORO_ID_Lavoro) REFERENCES LAVORO (ID_Lavoro)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);